//=========================================================
// inc/InitDevice.h: generated by Hardware Configurator
//
// This file will be regenerated when saving a document.
// leave the sections inside the "$[...]" comment tags alone
// or they will be overwritten!
//=========================================================
#ifndef __INIT_DEVICE_H__
#define __INIT_DEVICE_H__

// USER CONSTANTS
// USER PROTOTYPES

// $[Mode Transition Prototypes]
extern void
enter_DefaultMode_from_RESET (void);
// [Mode Transition Prototypes]$

// $[Config(Per-Module Mode)Transition Prototypes]
extern void WDT_0_enter_DefaultMode_from_RESET (void);
extern void PORTS_0_enter_DefaultMode_from_RESET (void);
extern void PORTS_1_enter_DefaultMode_from_RESET (void);
extern void PORTS_2_enter_DefaultMode_from_RESET (void);
extern void PBCFG_0_enter_DefaultMode_from_RESET (void);
extern void CLOCK_0_enter_DefaultMode_from_RESET (void);
extern void TIMER01_0_enter_DefaultMode_from_RESET (void);
extern void TIMER16_2_enter_DefaultMode_from_RESET (void);
extern void TIMER_SETUP_0_enter_DefaultMode_from_RESET (void);
extern void SMBUS_0_enter_DefaultMode_from_RESET (void);
extern void UART_0_enter_DefaultMode_from_RESET (void);
extern void INTERRUPT_0_enter_DefaultMode_from_RESET (void);
// [Config(Per-Module Mode)Transition Prototypes]$

typedef enum
{
  I2C0_TIMER0      = SMB0CF_SMBCS__TIMER0,      //!< Select SystemClock/12
  I2C0_TIMER1      = SMB0CF_SMBCS__TIMER1,      //!< Select SystemClock/4
  I2C0_TIMER2_HIGH = SMB0CF_SMBCS__TIMER2_HIGH, //!< Select Timer0 Overflow
  I2C0_TIMER2_LOW  = SMB0CF_SMBCS__TIMER2_LOW,  //!< Select ECI falling edge
} I2C0_Timebase_t;

extern idata unsigned char I2C0_BUF_OUT[8];
extern idata unsigned char I2C0_BUF_IN[8];

#endif

